local:
  algorithms:
    - Local
  models:
    - GIN
    - SAGPooling
    - EdgePooling
    - PANPooling

  common:
    num_clients: 5
    rounds: 50
    local_steps: 1
    batch_size: 32
    lr: 0.001
    optimizer: adam
